# 1 Madlibs

In [1]:
youtuber = 'abc'


print('Subscribe to ' + youtuber)
print('subscribe to {}'.format(youtuber))
print(f'subscribe to {youtuber}')

Subscribe to abc
subscribe to abc
subscribe to abc


In [2]:
adj = input('Adjective: ')
verb1 = input('Verb: ')

madlib = f'computer programming is so {adj}! It makes me so excited all the time because I love to {verb1}.'

madlib

Adjective: tiresome
Verb: sleep


'computer programming is so tiresome! It makes me so excited all the time because I love to sleep.'

# 2 Guess the number(computer)

In [3]:
import random

In [4]:
def guess(x):
    random_num = random.randint(1,x)
    guess = 0
    while guess != random_num:
        guess = int(input(f'Guess a number between 1 and {x}: '))
        if guess < random_num:
            print('too low')
            
        elif guess > random_num:
            print('too high')
        
        
    print(f'you guessed {random_num} right')
        

        
guess(10)

Guess a number between 1 and 10: 5
too high
Guess a number between 1 and 10: 2
too low
Guess a number between 1 and 10: 4
you guessed 4 right


# 3 Guess the number(user)

In [4]:
def comp_guess(x):
    low = 1
    high = x
    feedback = ''
    while feedback != 'c':
        if low != high:
            guess = random.randint(low,high)
        else:
            guess = low
        
        feedback = input(f"It's {guess} if high type H, low L, correct C: ").lower()
        if feedback == 'h':
            high = guess - 1
        elif feedback == 'l':
            low = guess + 1
    
    print(f'the number is {guess}')
    
    
    
comp_guess(10)

It's 8 if high type H, low L, correct C: 5
It's 10 if high type H, low L, correct C: C
the number is 10


# 4 Rock paper scissors

In [5]:
def play():
    
    user = input("Enter 'r' for rock, 's' for scissors, 'p' for papers\n ")
    comp = random.choice(['r', 'p', 's'])
    
    if user == comp:
        return print("It's a tie!")
    
    if win(user, comp):
        return print('you won!')
    
    
    return 'you lost'
    
    
def win(player, opp):
    if (player == 'r' and opp == 's') or (player == 'p' and opp == 'r') or (player == 's' and opp == 'p'):
        return True

In [6]:
play()

Enter 'r' for rock, 's' for scissors, 'p' for papers
 r
It's a tie!


# 5 Hangman

In [7]:
from words import words

import string

In [8]:
len(words)

2643

In [9]:
def get_valid_word(words):
    
    word = random.choice(words)
    
    while '-' in word or ' ' in word:
        word = random.choice(words)
        
    return word.upper()



def hangman():   

    word = get_valid_word(words)
    word_letters = set(word)
    alph = set(string.ascii_uppercase)
    used_letters = set()
    lives = 6

    while len(word_letters) >0 and lives > 0:

        print('you have ', lives, 'lives left and you have used these letters: ', ' '.join(used_letters))

        word_list = [letter if letter in used_letters else '-' for letter in word]

        print('current word: ', ' '.join(word_list))

        used_letter = input('Type a letter: ').upper()

        if used_letter in alph - used_letters:
            used_letters.add(used_letter)

            if used_letter in word_letters:
                word_letters.remove(used_letter)
                
            else:
                lives -= 1 
                print('letter is not in word')

        elif used_letter in used_letters:
            print('you already guessed that, please try again')
        else:
            print('invalid input')
        
        word_list = [letter if letter in used_letters else '-' for letter in word]

    if lives == 0:
        print("You ded bro XD , your dumbass couldn't even guess", word,'lol.')
    else:
        print('you guessed the word', word, '!!')





In [10]:
hangman()

you have  6 lives left and you have used these letters:  
current word:  - - - - -
Type a letter: r
letter is not in word
you have  5 lives left and you have used these letters:  R
current word:  - - - - -
Type a letter: a
letter is not in word
you have  4 lives left and you have used these letters:  A R
current word:  - - - - -
Type a letter: e
you have  4 lives left and you have used these letters:  A R E
current word:  - - E E -
Type a letter: s
you have  4 lives left and you have used these letters:  A R E S
current word:  S - E E -
Type a letter: l
letter is not in word
you have  3 lives left and you have used these letters:  L E S A R
current word:  S - E E -
Type a letter: t
you have  3 lives left and you have used these letters:  L E S A T R
current word:  S - E E T
Type a letter: k
letter is not in word
you have  2 lives left and you have used these letters:  L E S K A T R
current word:  S - E E T
Type a letter: w
you guessed the word SWEET !!


# 6 Tic-Tac-Toe

Player

In [12]:
import math
import random


class Player():
    def __init__(self, letter):
        self.letter = letter

    def get_move(self, game):
        pass


class HumanPlayer(Player):
    def __init__(self, letter):
        super().__init__(letter)

    def get_move(self, game):
        valid_square = False
        val = None
        while not valid_square:
            square = input(self.letter + '\'s turn. Input move (0-9): ')
            try:
                val = int(square)
                if val not in game.available_moves():
                    raise ValueError
                valid_square = True
            except ValueError:
                print('Invalid square. Try again.')
        return val


class RandomComputerPlayer(Player):
    def __init__(self, letter):
        super().__init__(letter)

    def get_move(self, game):
        square = random.choice(game.available_moves())
        return square


class GeniusCompPlayer(Player):
    def __init__(self,letter):
        super().__init__(letter)
    def get_move(self, game):

        if len(game.available_moves()) == 9:
            square = random.choice(game.available_moves())
        else:
            square = self.minimax(game, self.letter)['position']

        return square

    def minimax(self, state, player):
        max_player = self.letter  # yourself
        other_player = 'O' if player == 'X' else 'X'

        if state.current_winner == other_player:
            return {'position': None, 'score': 1 * (state.num_empty_squares() + 1) if other_player == max_player else -1 * (
                        state.num_empty_squares() + 1)}
        elif not state.empty_squares():
            return {'position': None, 'score': 0}

        if player == max_player:
            best = {'position': None, 'score': -math.inf}
        else:
            best = {'position': None, 'score': math.inf}
        for possible_move in state.available_moves():
            state.make_move(possible_move, player)
            sim_score = self.minimax(state, other_player)


            state.board[possible_move] = ' '
            state.current_winner = None
            sim_score['position'] = possible_move

            if player == max_player:
                if sim_score['score'] > best['score']:
                    best = sim_score
            else:
                if sim_score['score'] < best['score']:
                    best = sim_score
        return best


#### Game

In [14]:
import time

class TicTacToe():
    def __init__(self):
        self.board = self.make_board()
        self.current_winner = None

    @staticmethod
    def make_board():
        return [' ' for _ in range(9)]

    def print_board(self):
        for row in [self.board[i*3:(i+1) * 3] for i in range(3)]:
            print('| ' + ' | '.join(row) + ' |')

    @staticmethod
    def print_board_nums():
        # 0 | 1 | 2
        number_board = [[str(i) for i in range(j*3, (j+1)*3)] for j in range(3)]
        for row in number_board:
            print('| ' + ' | '.join(row) + ' |')

    def make_move(self, square, letter):
        if self.board[square] == ' ':
            self.board[square] = letter
            if self.winner(square, letter):
                self.current_winner = letter
            return True
        return False

    def winner(self, square, letter):
        # check the row
        row_ind = math.floor(square / 3)
        row = self.board[row_ind*3:(row_ind+1)*3]
        # print('row', row)
        if all([s == letter for s in row]):
            return True
        col_ind = square % 3
        column = [self.board[col_ind+i*3] for i in range(3)]
        # print('col', column)
        if all([s == letter for s in column]):
            return True
        if square % 2 == 0:
            diagonal1 = [self.board[i] for i in [0, 4, 8]]
            # print('diag1', diagonal1)
            if all([s == letter for s in diagonal1]):
                return True
            diagonal2 = [self.board[i] for i in [2, 4, 6]]
            # print('diag2', diagonal2)
            if all([s == letter for s in diagonal2]):
                return True
        return False

    def empty_squares(self):
        return ' ' in self.board

    def num_empty_squares(self):
        return self.board.count(' ')

    def available_moves(self):
        return [i for i, x in enumerate(self.board) if x == " "]


def play(game, x_player, o_player, print_game=True):

    if print_game:
        game.print_board_nums()

    letter = 'X'
    while game.empty_squares():
        if letter == 'O':
            square = o_player.get_move(game)
        else:
            square = x_player.get_move(game)
        if game.make_move(square, letter):

            if print_game:
                print(letter + ' makes a move to square {}'.format(square))
                game.print_board()
                print('')

            if game.current_winner:
                if print_game:
                    print(letter + ' wins!')
                return letter  # ends the loop and exits the game
            letter = 'O' if letter == 'X' else 'X'  # switches player

        time.sleep(.8)

    if print_game:
        print('It\'s a tie!')



if __name__ == '__main__':
    x_player = HumanPlayer('X')
    o_player = GeniusCompPlayer('O')
    t = TicTacToe()
    play(t, x_player, o_player, print_game=True)

| 0 | 1 | 2 |
| 3 | 4 | 5 |
| 6 | 7 | 8 |
X's turn. Input move (0-9): X
Invalid square. Try again.
X's turn. Input move (0-9): 4
X makes a move to square 4
|   |   |   |
|   | X |   |
|   |   |   |

O makes a move to square 5
|   |   |   |
|   | X | O |
|   |   |   |

X's turn. Input move (0-9): 8
X makes a move to square 8
|   |   |   |
|   | X | O |
|   |   | X |

O makes a move to square 3
|   |   |   |
| O | X | O |
|   |   | X |

X's turn. Input move (0-9): 0
X makes a move to square 0
| X |   |   |
| O | X | O |
|   |   | X |

X wins!


# 7 Binary Search

In [11]:
def naive_search(ls, target):
    for i in range(len(ls)):
        if ls[i] == target:
            return i
    return -1

def binary_search(ls, target, low = None, high=None):
    if low is None:
        low = 0
    if high is None:
        high = len(ls) - 1
    if high<low:
        return -1
    
    
    mid_pt = (low +high)// 2
    
    if ls[mid_pt]==target:
        
        return mid_pt
    
    
    elif target < ls[mid_pt]:
        return binary_search(ls, target, low, mid_pt -1)
    
    
    else:
        return binary_search(ls, target, mid_pt+1, high)
    
    
# if __name__ == '__main__':
l = [1,3,5,10,12]
target = 10
    
binary_search(l, target)

3

In [12]:
binary_search(l,10)

3

# 9 Minesweeper

In [26]:
import random
import re

class Board:
    def __init__(self, dim_size,num_bombs):
        
        self.dim_size = dim_size
        self.num_bombs = num_bombs


        self.board = self.make_new_board()
        self.assign_values_to_board()
        
        self.dug = set()
        
    def make_new_board(self):
        
        board = [[None for _ in range(self.dim_size)] for _ in range(self.dim_size)]
        bombs_planted = 0
            
        while bombs_planted < self.num_bombs:
            loc= random.randint(0, self.dim_size**2 -1)
            row = loc// self.dim_size
            col = loc % self.dim_size
                
            if board[row][col]=='*':
                continue
            board[row][col]=='*'
            bombs_planted += 1
                
        return board
        
    def assign_values_to_board(self):
        for r in range(self.dim_size):
            for c in range(self.dim_size):
                if self.board[r][c] == '*':
                    continue
                        
                self.board[r][c] = self.get_num_neighbouring_bombs(r,c)
        
    def get_num_neighbouring_bombs(self, row, col):
            
        num_neighbouring_bombs = 0
        for r in range(max(0, row-1), min(self.dim_size-1 ,row+1)+1):
            for c in range(max(0,col-1), min(self.dim_size-1,col+1)+1):
                if r == row and c == col:
                    continue
                               
                if self.board[r][c] == '*':
                    num_neighbouring_bombs += 1
        
        return num_neighbouring_bombs

    def dig(self, row, col):
        self.dug.add((row,col))
        
        if self.board[row][col] == '*':
            return False
        
        elif self.board[row][col]>0:
            return True
        
        for r in range(max(0, row-1), min(self.dim_size,row+1)+1):
            for c in range(max(0,col-1), min(self.dim_size,col+1)+1):
                if(r,c) in self.dug:
                    
                    continue
                self.dig(r,c)
                
        return True
    
    def __str__(self):
        visible_board = [[None for _ in range(self.dim_size)]for _ in range(self.dim_size)]
        
        for row in range(self.dim_size):
            for col in range(self.dim_size):
                if (row,col) in self.dug:
                    visible_board[row][col]= str(self.board[row][col])
                else:
                    visible_board[row][col] = ' '
                    
        string_rep = ''
        widths = []
        
        for idx in range(self.dim_size):
            columns = map(lambda x: x[idx], visible_board)
            widths.append(len(max(columns, key = len)))
            
        
        indices = [i for i in range(self.dim_size)]
        indices_row = '   '
        cells = []
        for idx, col in enumerate(indices):
            format = '%-'+ str(widths[idx]) + 's'
            cells.append(format % (col))
        indices_row += '  '.join(cells)
        indices_row += '  \n'
        
        for i in range(len(visible_board)):
            row = visible_board[i]
            string_rep += f'{i} |'
            cells = []
            for idx, col in enumerate(row):
                format = '%-' + str(widths[idx]) + "s"
                cells.append(format % (col))
            string_rep += ' |'.join(cells)
            string_rep += ' |\n'

        str_len = int(len(string_rep) / self.dim_size)
        string_rep = indices_row + '-'*str_len + '\n' + string_rep + '-'*str_len

        return string_rep


def play(dim_size = 10, num_bombs = 10):
    board = Board(dim_size,num_bombs)
    
    
    safe = True
    
    while len(board.dug) < board.dim_size**2 - num_bombs:
        print(board)
        user_input = re.split(',(\\s)*',input('Where to dig? input as row,col: '))
        row, col = int(user_input[0]), int(user_input[-1])
        if row < 0 or row >= board.dim_size or col< 0 or col >= dim_size:
            print('invalid location, try again')
            
        safe = board.dig(row,col)
        if not safe:
                
            break
                
    if safe:
        print('you win')
    else:
        print('game over')
        
        board.dug = [(r,c) for r in range(board.dim_size) for c in range(board.dim_size)]
        
        print(board)
        
play()

   0  1  2  3  4  5  6  7  8  9  
----------------------------------
0 |  |  |  |  |  |  |  |  |  |  |
1 |  |  |  |  |  |  |  |  |  |  |
2 |  |  |  |  |  |  |  |  |  |  |
3 |  |  |  |  |  |  |  |  |  |  |
4 |  |  |  |  |  |  |  |  |  |  |
5 |  |  |  |  |  |  |  |  |  |  |
6 |  |  |  |  |  |  |  |  |  |  |
7 |  |  |  |  |  |  |  |  |  |  |
8 |  |  |  |  |  |  |  |  |  |  |
9 |  |  |  |  |  |  |  |  |  |  |
----------------------------------
Where to dig? input as row,col: 0,0


IndexError: list index out of range

# 10. Sudoku Solver

In [17]:
import numpy as np

In [19]:
def find_next_empty(puzzle):
    
    
    for r in range(9):
        for c in range(9):
            if puzzle[r][c] == -1:
                return r,c
            
    return None,None

def is_valid(puzzle,guess, row, col):
    row_vals = puzzle[row]
    if guess in row_vals:
        
        return False
    
    col_vals = [puzzle[i][col] for i in range(9)]
    if guess in col_vals:
        return False
    
    row_start = (row//3)*3
    
    col_start = (col//3)*3
    
    for r in range(row_start, row_start+3):
        for c in range(col_start, col_start+3):
            if puzzle[r][c]== guess:
                return False
    return True

def solve_sudoku(puzzle):
    
    
    row,col = find_next_empty(puzzle)
    /
    if row is None:
        return True
    
    for guess in range(1,10):
        if is_valid(puzzle,guess, row, col):
            puzzle[row][col] = guess
            
            if solve_sudoku(puzzle):
                return True
            
        puzzle[row][col] = -1
        
        
    return False
            

In [20]:
example_board = [
        [3, 9, -1,   -1, 5, -1,   -1, -1, -1],
        [-1, -1, -1,   2, -1, -1,   -1, -1, 5],
        [-1, -1, -1,   7, 1, 9,   -1, 8, -1],

        [-1, 5, -1,   -1, 6, 8,   -1, -1, -1],
        [2, -1, 6,   -1, -1, 3,   -1, -1, -1],
        [-1, -1, -1,   -1, -1, -1,   -1, -1, 4],

        [5, -1, -1,   -1, -1, -1,   -1, -1, -1],
        [6, 7, -1,   1, -1, 5,   -1, 4, -1],
        [1, -1, 9,   -1, -1, -1,   2, -1, -1]
    ]
print(solve_sudoku(example_board))

print(np.array(example_board))

True
[[3 9 1 8 5 6 4 2 7]
 [8 6 7 2 3 4 9 1 5]
 [4 2 5 7 1 9 6 8 3]
 [7 5 4 9 6 8 1 3 2]
 [2 1 6 4 7 3 5 9 8]
 [9 3 8 5 2 1 7 6 4]
 [5 4 3 6 9 2 8 7 1]
 [6 7 2 1 8 5 3 4 9]
 [1 8 9 3 4 7 2 5 6]]
